#!/usr/bin/env python3
"""
Generate a self-contained Docker Compose file for OpenCloud.

Usage:
    python3 generate-compose.py <base-domain> [options]

Examples:
    python3 generate-compose.py example.com
    python3 generate-compose.py example.com --admin-password secret -f docker-compose.generated.yml

The OpenCloud service will be accessible at https://cloud.<base-domain>.
"""

import argparse
import sys

OPENCLOUD_TAG = "5.2.0"
OPENCLOUD_IMAGE = "opencloudeu/opencloud-rolling"


def generate(domain: str, admin_password: str, oc_tag: str) -> str:
    oc_domain = f"cloud.{domain}"
    return f"""\
---
# Generated by generate-compose.py
# OpenCloud on {oc_domain}, exposed on port 9200 for an upstream reverse proxy (no Traefik).

services:
  opencloud:
    image: {OPENCLOUD_IMAGE}:{oc_tag}
    user: "1000:1000"
    networks:
      - opencloud-net
    entrypoint:
      - /bin/sh
    command: ["-c", "opencloud init || true; opencloud server"]
    environment:
      OC_URL: "https://{oc_domain}"
      OC_LOG_LEVEL: "info"
      OC_LOG_COLOR: "false"
      OC_LOG_PRETTY: "false"
      # No SSL between reverse proxy and OpenCloud
      PROXY_TLS: "false"
      # Bind to all interfaces so the host can reach port 9200
      PROXY_HTTP_ADDR: "0.0.0.0:9200"
      OC_INSECURE: "false"
      PROXY_ENABLE_BASIC_AUTH: "false"
      IDM_CREATE_DEMO_USERS: "false"
      IDM_ADMIN_PASSWORD: "{admin_password}"
      NOTIFICATIONS_SMTP_HOST: ""
      NOTIFICATIONS_SMTP_PORT: ""
      NOTIFICATIONS_SMTP_SENDER: "OpenCloud Notifications <notifications@{oc_domain}>"
      NOTIFICATIONS_SMTP_USERNAME: ""
      NOTIFICATIONS_SMTP_PASSWORD: ""
      NOTIFICATIONS_SMTP_INSECURE: "false"
      NOTIFICATIONS_SMTP_AUTHENTICATION: ""
      NOTIFICATIONS_SMTP_ENCRYPTION: "none"
      FRONTEND_ARCHIVER_MAX_SIZE: "10000000000"
      FRONTEND_CHECK_FOR_UPDATES: "true"
      PROXY_CSP_CONFIG_FILE_LOCATION: /etc/opencloud/csp.yaml
      OC_PASSWORD_POLICY_BANNED_PASSWORDS_LIST: banned-password-list.txt
      OC_SHARING_PUBLIC_SHARE_MUST_HAVE_PASSWORD: "true"
      OC_SHARING_PUBLIC_WRITEABLE_SHARE_MUST_HAVE_PASSWORD: "false"
      OC_PASSWORD_POLICY_DISABLED: "false"
      OC_PASSWORD_POLICY_MIN_CHARACTERS: "8"
      OC_PASSWORD_POLICY_MIN_LOWERCASE_CHARACTERS: "1"
      OC_PASSWORD_POLICY_MIN_UPPERCASE_CHARACTERS: "1"
      OC_PASSWORD_POLICY_MIN_DIGITS: "1"
      OC_PASSWORD_POLICY_MIN_SPECIAL_CHARACTERS: "1"
    ports:
      - "9200:9200"
    volumes:
      - ./config/opencloud/csp.yaml:/etc/opencloud/csp.yaml
      - ./config/opencloud/banned-password-list.txt:/etc/opencloud/banned-password-list.txt
      - opencloud-config:/etc/opencloud
      - opencloud-data:/var/lib/opencloud
      - ./config/opencloud/apps:/var/lib/opencloud/web/assets/apps
    logging:
      driver: local
    restart: always

volumes:
  opencloud-config:
  opencloud-data:

networks:
  opencloud-net:
"""


def main():
    parser = argparse.ArgumentParser(
        description="Generate a self-contained OpenCloud Docker Compose file."
    )
    parser.add_argument("domain", help="The public domain for OpenCloud, e.g. cloud.example.com")
    parser.add_argument(
        "--admin-password",
        default="changeme",
        help="Initial admin password (default: changeme)",
    )
    parser.add_argument(
        "--tag",
        default=OPENCLOUD_TAG,
        help=f"OpenCloud image tag (default: {OPENCLOUD_TAG})",
    )
    parser.add_argument(
        "-f",
        "--file",
        metavar="FILE",
        help="Write output to FILE instead of stdout",
    )

    args = parser.parse_args()

    content = generate(args.domain, args.admin_password, args.tag)

    if args.file:
        with open(args.file, "w") as fh:
            fh.write(content)
        print(f"Written to {args.file}", file=sys.stderr)
    else:
        sys.stdout.write(content)


if __name__ == "__main__":
    main()
